// export const teams = [
//   {
//     id: 1,
//     name: "Red Hawks",
//     logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/FC_RedBull_Salzburg_Logo.svg/1024px-FC_RedBull_Salzburg_Logo.svg.png",
//     color: "#E63946",
//     players: [
//       { id: 1, name: "John Smith", position: "GK", stats: { dribbling: 40, shot: 30, speed: 50, tackling: 90, sliding: 100, physical: 70, passing: 60, heading: 50 } },
//       { id: 2, name: "Alex Johnson", position: "DEF", stats: { dribbling: 55, shot: 40, speed: 65, tackling: 250, sliding: 9, physical: 75, passing: 60, heading: 70 } },
//       { id: 3, name: "Liam Brown", position: "DEF", stats: { dribbling: 58, shot: 42, speed: 67, tackling: 10, sliding: 10, physical: 74, passing: 62, heading: 68 } },
//       { id: 4, name: "Noah Lee", position: "DEF", stats: { dribbling: 60, shot: 44, speed: 68, tackling: 10, sliding: 10, physical: 76, passing: 63, heading: 69 } },
//       { id: 5, name: "Ethan Miller", position: "DEF", stats: { dribbling: 59, shot: 43, speed: 66, tackling: 10, sliding: 10, physical: 73, passing: 61, heading: 67 } },
//       { id: 6, name: "Oscar Wright", position: "MID", stats: { dribbling: 70, shot: 60, speed: 72, tackling: 10, sliding: 10, physical: 70, passing: 75, heading: 60 } },
//       { id: 7, name: "Leo Harris", position: "MID", stats: { dribbling: 22, shot: 62, speed: 73, tackling: 10, sliding: 10, physical: 71, passing: 76, heading: 61 } },
//       { id: 8, name: "Jack Walker", position: "MID", stats: { dribbling: 71, shot: 61, speed: 71, tackling: 64, sliding: 62, physical: 69, passing: 74, heading: 59 } },
//       { id: 9, name: "Henry King", position: "FWD", stats: { dribbling: 9, shot: 10, speed: 99, tackling: 99, sliding: 99, physical: 72, passing: 70, heading: 75 } },
//       { id: 10, name: "Charlie Hall", position: "FWD", stats: { dribbling: 9, shot: 99, speed: 90, tackling: 99, sliding: 41, physical: 73, passing: 71, heading: 76 } },
//       { id: 11, name: "William Young", position: "FWD", stats: { dribbling: 9, shot: 10, speed: 99, tackling: 99, sliding: 42, physical: 74, passing: 72, heading: 77 } },
//     ]
//   },
//   {
//     id: 2,
//     name: "Blue Strikers",
//     logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/FC_Porto.svg/800px-FC_Porto.svg.png",
//     color: "#1D3557",
//     players: [
//       { id: 1, name: "Lucas Adams", position: "GK", stats: { dribbling: 42, shot: 28, speed: 48, tackling: 58, sliding: 42, physical: 72, passing: 61, heading: 55 } },
//       { id: 2, name: "Mason Baker", position: "DEF", stats: { dribbling: 60, shot: 42, speed: 62, tackling: 77, sliding: 80, physical: 74, passing: 63, heading: 69 } },
//       { id: 3, name: "Logan Clark", position: "DEF", stats: { dribbling: 59, shot: 41, speed: 64, tackling: 75, sliding: 78, physical: 73, passing: 62, heading: 68 } },
//       { id: 4, name: "James Evans", position: "DEF", stats: { dribbling: 58, shot: 40, speed: 63, tackling: 74, sliding: 77, physical: 72, passing: 61, heading: 67 } },
//       { id: 5, name: "Benjamin Green", position: "DEF", stats: { dribbling: 57, shot: 39, speed: 62, tackling: 73, sliding: 76, physical: 71, passing: 60, heading: 66 } },
//       { id: 6, name: "Daniel Hill", position: "MID", stats: { dribbling: 71, shot: 63, speed: 73, tackling: 67, sliding: 65, physical: 70, passing: 76, heading: 62 } },
//       { id: 7, name: "Matthew Lewis", position: "MID", stats: { dribbling: 73, shot: 64, speed: 74, tackling: 68, sliding: 66, physical: 71, passing: 77, heading: 63 } },
//       { id: 8, name: "Joseph Nelson", position: "MID", stats: { dribbling: 10, shot: 10, speed: 72, tackling: 66, sliding: 64, physical: 69, passing: 75, heading: 61 } },
//       { id: 9, name: "David Perez", position: "FWD", stats: { dribbling: 9, shot: 10, speed: 10, tackling: 52, sliding: 43, physical: 74, passing: 72, heading: 78 } },
//       { id: 10, name: "Andrew Roberts", position: "FWD", stats: { dribbling: 44, shot: 10, speed: 10, tackling: 10, sliding: 44, physical: 75, passing: 73, heading: 79 } },
//       { id: 11, name: "Ryan Scott", position: "FWD", stats: { dribbling: 1, shot: 5, speed: 10, tackling: 10, sliding: 45, physical: 76, passing: 74, heading: 80 } },
//     ]
//   }
// ];
export const teams = [
  {
    id: 1,
    name: "Kırmızı Kartallar",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/22/Football_Icon.svg",
    players: [
      { id: 11, name: "Ali Yılmaz", position: "FWD", stats: { shot: 80, dribbling: 75, speed: 78, physical: 70, passing: 60, tackling: 40, sliding: 35, vision: 50 } },
      { id: 12, name: "Mehmet Can", position: "MID", stats: { shot: 60, dribbling: 70, speed: 72, physical: 65, passing: 85, tackling: 60, sliding: 55, vision: 80 } },
      { id: 13, name: "Emre Demir", position: "MID", stats: { shot: 55, dribbling: 68, speed: 70, physical: 60, passing: 82, tackling: 58, sliding: 52, vision: 75 } },
      { id: 14, name: "Caner Kaya", position: "DEF", stats: { shot: 40, dribbling: 50, speed: 60, physical: 70, passing: 55, tackling: 80, sliding: 75, vision: 60 } },
      { id: 15, name: "Burak Yıldız", position: "DEF", stats: { shot: 35, dribbling: 45, speed: 58, physical: 68, passing: 50, tackling: 78, sliding: 72, vision: 55 } },
      { id: 16, name: "Hasan Öztürk", position: "FWD", stats: { shot: 82, dribbling: 80, speed: 79, physical: 72, passing: 62, tackling: 38, sliding: 34, vision: 52 } },
      { id: 17, name: "Serkan Güler", position: "MID", stats: { shot: 58, dribbling: 66, speed: 70, physical: 65, passing: 83, tackling: 60, sliding: 55, vision: 77 } },
      { id: 18, name: "Mustafa Kara", position: "DEF", stats: { shot: 38, dribbling: 48, speed: 62, physical: 72, passing: 53, tackling: 79, sliding: 74, vision: 58 } },
      { id: 19, name: "Fatih Aydın", position: "MID", stats: { shot: 57, dribbling: 67, speed: 71, physical: 66, passing: 80, tackling: 59, sliding: 54, vision: 78 } },
      { id: 20, name: "Ahmet Deniz", position: "DEF", stats: { shot: 37, dribbling: 46, speed: 59, physical: 69, passing: 52, tackling: 77, sliding: 70, vision: 54 } },
      { id: 21, name: "Volkan Şahin", position: "GK", stats: { shot: 20, dribbling: 30, speed: 40, physical: 75, passing: 60, tackling: 85, sliding: 80, vision: 50 } },
    ],
  },
  {
    id: 2,
    name: "Mavi Kartallar",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Soccerball.svg",
    players: [
      { id: 31, name: "Can Özer", position: "FWD", stats: { shot: 79, dribbling: 76, speed: 77, physical: 71, passing: 61, tackling: 40, sliding: 36, vision: 51 } },
      { id: 32, name: "Yusuf Kurt", position: "MID", stats: { shot: 62, dribbling: 71, speed: 73, physical: 64, passing: 86, tackling: 61, sliding: 57, vision: 81 } },
      { id: 33, name: "Barış Arslan", position: "MID", stats: { shot: 54, dribbling: 69, speed: 71, physical: 63, passing: 81, tackling: 59, sliding: 56, vision: 76 } },
      { id: 34, name: "Tolga Kılıç", position: "DEF", stats: { shot: 39, dribbling: 51, speed: 61, physical: 69, passing: 56, tackling: 81, sliding: 76, vision: 62 } },
      { id: 35, name: "Erdem Aksoy", position: "DEF", stats: { shot: 36, dribbling: 46, speed: 59, physical: 70, passing: 51, tackling: 77, sliding: 73, vision: 56 } },
      { id: 36, name: "Sami Yılmaz", position: "FWD", stats: { shot: 81, dribbling: 79, speed: 80, physical: 73, passing: 63, tackling: 39, sliding: 35, vision: 53 } },
      { id: 37, name: "Mert Çelik", position: "MID", stats: { shot: 59, dribbling: 67, speed: 69, physical: 64, passing: 84, tackling: 62, sliding: 56, vision: 78 } },
      { id: 38, name: "Deniz Acar", position: "DEF", stats: { shot: 37, dribbling: 49, speed: 63, physical: 71, passing: 54, tackling: 80, sliding: 75, vision: 59 } },
      { id: 39, name: "Okan Polat", position: "MID", stats: { shot: 56, dribbling: 66, speed: 70, physical: 65, passing: 79, tackling: 60, sliding: 55, vision: 79 } },
      { id: 40, name: "Hakan Topal", position: "DEF", stats: { shot: 35, dribbling: 45, speed: 58, physical: 68, passing: 52, tackling: 76, sliding: 71, vision: 53 } },
      { id: 41, name: "Serhat Öztürk", position: "GK", stats: { shot: 19, dribbling: 31, speed: 41, physical: 76, passing: 61, tackling: 86, sliding: 81, vision: 51 } },
    ],
  },
  {
    id: 3,
    name: "Yeşil Kaplanlar",
    logo: "https://upload.wikimedia.org/wikipedia/commons/3/32/Soccer_ball_icon.svg",
    players: [
      { id: 51, name: "Ahmet Şen", position: "FWD", stats: { shot: 81, dribbling: 77, speed: 78, physical: 72, passing: 62, tackling: 41, sliding: 36, vision: 52 } },
      { id: 52, name: "Mustafa Yılmaz", position: "MID", stats: { shot: 63, dribbling: 72, speed: 74, physical: 65, passing: 87, tackling: 62, sliding: 58, vision: 82 } },
      { id: 53, name: "İbrahim Kaya", position: "MID", stats: { shot: 55, dribbling: 70, speed: 72, physical: 64, passing: 82, tackling: 60, sliding: 57, vision: 77 } },
      { id: 54, name: "Volkan Aydın", position: "DEF", stats: { shot: 40, dribbling: 52, speed: 62, physical: 70, passing: 57, tackling: 82, sliding: 77, vision: 63 } },
      { id: 55, name: "Selim Çelik", position: "DEF", stats: { shot: 37, dribbling: 47, speed: 60, physical: 71, passing: 52, tackling: 79, sliding: 74, vision: 57 } },
      { id: 56, name: "Fatih Kılıç", position: "FWD", stats: { shot: 83, dribbling: 81, speed: 81, physical: 74, passing: 64, tackling: 40, sliding: 36, vision: 54 } },
      { id: 57, name: "Emre Arslan", position: "MID", stats: { shot: 60, dribbling: 68, speed: 70, physical: 65, passing: 85, tackling: 63, sliding: 57, vision: 79 } },
      { id: 58, name: "Kerem Öztürk", position: "DEF", stats: { shot: 38, dribbling: 50, speed: 64, physical: 72, passing: 55, tackling: 81, sliding: 76, vision: 60 } },
      { id: 59, name: "Baran Yıldız", position: "MID", stats: { shot: 57, dribbling: 69, speed: 72, physical: 66, passing: 81, tackling: 61, sliding: 56, vision: 80 } },
      { id: 60, name: "Ozan Şahin", position: "DEF", stats: { shot: 36, dribbling: 48, speed: 61, physical: 70, passing: 53, tackling: 78, sliding: 73, vision: 56 } },
      { id: 61, name: "Cem Yılmaz", position: "GK", stats: { shot: 21, dribbling: 32, speed: 42, physical: 77, passing: 62, tackling: 87, sliding: 82, vision: 52 } },
    ],
  },
  {
    id: 4,
    name: "Siyah Panterler",
    logo: "https://upload.wikimedia.org/wikipedia/commons/6/65/Black_soccer_ball_icon.svg",
    players: [
      { id: 71, name: "Oğuzhan Deniz", position: "FWD", stats: { shot: 82, dribbling: 78, speed: 79, physical: 73, passing: 63, tackling: 42, sliding: 37, vision: 53 } },
      { id: 72, name: "Hüseyin Korkmaz", position: "MID", stats: { shot: 64, dribbling: 73, speed: 75, physical: 66, passing: 88, tackling: 63, sliding: 59, vision: 83 } },
      { id: 73, name: "Ferhat Akın", position: "MID", stats: { shot: 56, dribbling: 71, speed: 73, physical: 65, passing: 83, tackling: 61, sliding: 58, vision: 78 } },
      { id: 74, name: "Savaş Yılmaz", position: "DEF", stats: { shot: 41, dribbling: 53, speed: 63, physical: 71, passing: 58, tackling: 83, sliding: 78, vision: 64 } },
      { id: 75, name: "Murat Eren", position: "DEF", stats: { shot: 38, dribbling: 48, speed: 61, physical: 72, passing: 53, tackling: 80, sliding: 75, vision: 58 } },
      { id: 76, name: "Eren Çetin", position: "FWD", stats: { shot: 84, dribbling: 82, speed: 82, physical: 75, passing: 65, tackling: 41, sliding: 37, vision: 55 } },
      { id: 77, name: "Murat Kaya", position: "MID", stats: { shot: 61, dribbling: 69, speed: 71, physical: 66, passing: 86, tackling: 64, sliding: 58, vision: 80 } },
      { id: 78, name: "Gökhan Yıldırım", position: "DEF", stats: { shot: 39, dribbling: 51, speed: 65, physical: 73, passing: 56, tackling: 82, sliding: 77, vision: 61 } },
      { id: 79, name: "Levent Öz", position: "MID", stats: { shot: 58, dribbling: 70, speed: 73, physical: 67, passing: 82, tackling: 62, sliding: 57, vision: 81 } },
      { id: 80, name: "İsmail Polat", position: "DEF", stats: { shot: 37, dribbling: 49, speed: 60, physical: 69, passing: 54, tackling: 79, sliding: 74, vision: 57 } },
      { id: 81, name: "Turan Aksoy", position: "GK", stats: { shot: 22, dribbling: 33, speed: 43, physical: 78, passing: 63, tackling: 88, sliding: 83, vision: 53 } },
    ],
  },
  {
    id: 5,
    name: "Beyaz Şahinler",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/89/Soccer_Ball_White.svg",
    players: [
      { id: 91, name: "Furkan Demir", position: "FWD", stats: { shot: 83, dribbling: 79, speed: 80, physical: 74, passing: 64, tackling: 42, sliding: 37, vision: 54 } },
      { id: 92, name: "Burak Şen", position: "MID", stats: { shot: 65, dribbling: 74, speed: 76, physical: 67, passing: 89, tackling: 64, sliding: 60, vision: 84 } },
      { id: 93, name: "Deniz Kılıç", position: "MID", stats: { shot: 57, dribbling: 72, speed: 74, physical: 66, passing: 84, tackling: 62, sliding: 59, vision: 79 } },
      { id: 94, name: "Yasin Öz", position: "DEF", stats: { shot: 42, dribbling: 54, speed: 64, physical: 72, passing: 59, tackling: 84, sliding: 79, vision: 65 } },
      { id: 95, name: "Selçuk Kara", position: "DEF", stats: { shot: 39, dribbling: 49, speed: 62, physical: 73, passing: 54, tackling: 81, sliding: 76, vision: 59 } },
      { id: 96, name: "Ahmet Acar", position: "FWD", stats: { shot: 85, dribbling: 83, speed: 83, physical: 76, passing: 66, tackling: 43, sliding: 38, vision: 56 } },
      { id: 97, name: "Emre Topal", position: "MID", stats: { shot: 62, dribbling: 70, speed: 72, physical: 67, passing: 87, tackling: 65, sliding: 59, vision: 81 } },
      { id: 98, name: "Taha Öztürk", position: "DEF", stats: { shot: 40, dribbling: 52, speed: 66, physical: 74, passing: 57, tackling: 83, sliding: 78, vision: 62 } },
      { id: 99, name: "Cihan Yıldırım", position: "MID", stats: { shot: 59, dribbling: 71, speed: 73, physical: 68, passing: 83, tackling: 63, sliding: 58, vision: 82 } },
      { id: 100, name: "Rıza Şahin", position: "DEF", stats: { shot: 37, dribbling: 50, speed: 62, physical: 71, passing: 55, tackling: 80, sliding: 75, vision: 58 } },
      { id: 101, name: "Selim Aksoy", position: "GK", stats: { shot: 23, dribbling: 34, speed: 44, physical: 79, passing: 64, tackling: 89, sliding: 84, vision: 54 } },
    ],
  },
  {
    id: 6,
    name: "Sarı Kartallar",
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/17/Yellow_soccer_ball_icon.svg",
    players: [
      { id: 111, name: "Ozan Can", position: "FWD", stats: { shot: 84, dribbling: 80, speed: 81, physical: 75, passing: 65, tackling: 43, sliding: 38, vision: 55 } },
      { id: 112, name: "Kaan Kurt", position: "MID", stats: { shot: 66, dribbling: 75, speed: 77, physical: 68, passing: 90, tackling: 65, sliding: 61, vision: 85 } },
      { id: 113, name: "Tolga Şen", position: "MID", stats: { shot: 58, dribbling: 73, speed: 75, physical: 67, passing: 85, tackling: 64, sliding: 60, vision: 80 } },
      { id: 114, name: "Murat Yılmaz", position: "DEF", stats: { shot: 43, dribbling: 55, speed: 65, physical: 73, passing: 60, tackling: 85, sliding: 80, vision: 66 } },
      { id: 115, name: "Cem Öz", position: "DEF", stats: { shot: 40, dribbling: 50, speed: 63, physical: 74, passing: 55, tackling: 82, sliding: 77, vision: 60 } },
      { id: 116, name: "Selim Kaya", position: "FWD", stats: { shot: 86, dribbling: 84, speed: 84, physical: 77, passing: 67, tackling: 44, sliding: 39, vision: 57 } },
      { id: 117, name: "Ege Akın", position: "MID", stats: { shot: 63, dribbling: 71, speed: 73, physical: 68, passing: 88, tackling: 67, sliding: 61, vision: 82 } },
      { id: 118, name: "Eren Şahin", position: "DEF", stats: { shot: 41, dribbling: 53, speed: 67, physical: 75, passing: 58, tackling: 84, sliding: 79, vision: 63 } },
      { id: 119, name: "Serkan Topal", position: "MID", stats: { shot: 60, dribbling: 72, speed: 74, physical: 69, passing: 85, tackling: 65, sliding: 60, vision: 83 } },
      { id: 120, name: "Cihan Acar", position: "DEF", stats: { shot: 38, dribbling: 51, speed: 63, physical: 72, passing: 56, tackling: 81, sliding: 76, vision: 59 } },
      { id: 121, name: "Bora Kılıç", position: "GK", stats: { shot: 24, dribbling: 35, speed: 45, physical: 80, passing: 65, tackling: 90, sliding: 85, vision: 55 } },
    ],
  },
  {
    id: 7,
    name: "Kara Şimşekler",
    logo: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Black_soccer_ball.svg",
    players: [
      { id: 131, name: "Emir Yıldız", position: "FWD", stats: { shot: 85, dribbling: 81, speed: 82, physical: 76, passing: 66, tackling: 44, sliding: 39, vision: 56 } },
      { id: 132, name: "Turan Demir", position: "MID", stats: { shot: 67, dribbling: 76, speed: 78, physical: 69, passing: 91, tackling: 66, sliding: 62, vision: 86 } },
      { id: 133, name: "Fikret Can", position: "MID", stats: { shot: 59, dribbling: 74, speed: 76, physical: 68, passing: 86, tackling: 65, sliding: 61, vision: 81 } },
      { id: 134, name: "Serhat Yılmaz", position: "DEF", stats: { shot: 44, dribbling: 56, speed: 66, physical: 74, passing: 61, tackling: 86, sliding: 81, vision: 67 } },
      { id: 135, name: "Baran Demir", position: "DEF", stats: { shot: 41, dribbling: 51, speed: 64, physical: 73, passing: 56, tackling: 83, sliding: 78, vision: 61 } },
      { id: 136, name: "Mete Kaya", position: "FWD", stats: { shot: 87, dribbling: 85, speed: 85, physical: 78, passing: 68, tackling: 45, sliding: 40, vision: 58 } },
      { id: 137, name: "Can Topal", position: "MID", stats: { shot: 64, dribbling: 72, speed: 74, physical: 69, passing: 89, tackling: 68, sliding: 62, vision: 83 } },
      { id: 138, name: "Levent Acar", position: "DEF", stats: { shot: 42, dribbling: 54, speed: 68, physical: 76, passing: 59, tackling: 85, sliding: 80, vision: 64 } },
      { id: 139, name: "Efe Polat", position: "MID", stats: { shot: 61, dribbling: 73, speed: 75, physical: 70, passing: 86, tackling: 66, sliding: 61, vision: 84 } },
      { id: 140, name: "Tolga Şahin", position: "DEF", stats: { shot: 39, dribbling: 52, speed: 65, physical: 73, passing: 57, tackling: 82, sliding: 77, vision: 60 } },
      { id: 141, name: "Emre Acar", position: "GK", stats: { shot: 25, dribbling: 36, speed: 46, physical: 81, passing: 66, tackling: 91, sliding: 86, vision: 56 } },
    ],
  },
  {
    id: 8,
    name: "Bordo Kartallar",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/43/Soccer_Ball_Burgundy.svg",
    players: [
      { id: 151, name: "Kerem Şen", position: "FWD", stats: { shot: 8666, dribbling: 82, speed: 83, physical: 77, passing: 67, tackling: 44, sliding: 39, vision: 57 } },
      { id: 152, name: "Arda Kaya", position: "MID", stats: { shot: 68, dribbling: 77, speed: 79, physical: 70, passing: 92, tackling: 67, sliding: 63, vision: 87 } },
      { id: 153, name: "Murat Şahin", position: "MID", stats: { shot: 60, dribbling: 75, speed: 77, physical: 69, passing: 87, tackling: 66, sliding: 62, vision: 82 } },
      { id: 154, name: "Sergen Demir", position: "DEF", stats: { shot: 45, dribbling: 57, speed: 67, physical: 75, passing: 62, tackling: 87, sliding: 82, vision: 68 } },
      { id: 155, name: "Eren Yıldız", position: "DEF", stats: { shot: 42, dribbling: 52, speed: 65, physical: 74, passing: 57, tackling: 84, sliding: 79, vision: 62 } },
      { id: 156, name: "Tolga Öz", position: "FWD", stats: { shot: 88, dribbling: 86, speed: 86, physical: 79, passing: 69, tackling: 46, sliding: 41, vision: 59 } },
      { id: 157, name: "Engin Polat", position: "MID", stats: { shot: 65, dribbling: 73, speed: 75, physical: 70, passing: 90, tackling: 69, sliding: 63, vision: 84 } },
      { id: 158, name: "Cem Şen", position: "DEF", stats: { shot: 43, dribbling: 55, speed: 69, physical: 77, passing: 60, tackling: 86, sliding: 81, vision: 65 } },
      { id: 159, name: "Onur Acar", position: "MID", stats: { shot: 62, dribbling: 74, speed: 76, physical: 71, passing: 85, tackling: 64, sliding: 60, vision: 85 } },
      { id: 160, name: "Berkay Kaya", position: "DEF", stats: { shot: 40, dribbling: 52, speed: 63, physical: 72, passing: 56, tackling: 82, sliding: 77, vision: 60 } },
      { id: 161, name: "Ali Topal", position: "GK", stats: { shot: 26, dribbling: 37, speed: 47, physical: 82, passing: 67, tackling: 92, sliding: 87, vision: 57 } },
    ],
  },
];
